# Generated by Django 3.2 on 2024-10-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('denominacionOrigen', models.CharField(max_length=50)),
                ('cantidadProducto', models.IntegerField(max_length=15)),
            ],
        ),
    ]
