# Generated by Django 3.2 on 2024-11-01 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('idDistribuidor', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('ciudad', models.CharField(max_length=15)),
                ('fechaDespacho', models.DateField()),
                ('fechaRecepcion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idFactura', models.AutoField(primary_key=True, serialize=False)),
                ('fechaFacturacion', models.DateField()),
                ('precioUnitario', models.FloatField(max_length=15)),
                ('iva', models.FloatField(max_length=15)),
                ('descuentoTotal', models.FloatField(max_length=15)),
                ('totalApagar', models.FloatField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='productos',
            name='id',
        ),
        migrations.AddField(
            model_name='productos',
            name='idProducto',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cantidadProducto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(max_length=50),
        ),
        migrations.AddField(
            model_name='productos',
            name='distribuidor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productoApp.distribuidor'),
        ),
        migrations.AddField(
            model_name='productos',
            name='factura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productoApp.factura'),
        ),
    ]
