# Generated by Django 3.2 on 2024-11-04 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='totalApagar',
        ),
        migrations.AlterField(
            model_name='factura',
            name='distribuidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='productoApp.distribuidor'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='distribuidores',
            field=models.ManyToManyField(blank=True, null=True, related_name='productos', to='productoApp.Distribuidor'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='facturas',
            field=models.ManyToManyField(blank=True, null=True, related_name='productos', to='productoApp.Factura'),
        ),
    ]
