# Generated by Django 3.2 on 2024-11-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productoApp', '0002_auto_20241101_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='idProducto',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
